### ISSUE TITLE
Slow response from API

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#185]
Returning /api/run-requests/ takes ~20 seconds on a server instance running on google cloud with mysql database. Currently this has 18 runrequests, and it seems to slow down as more runrequests are added. This is slow enough to cause timeout errors on clients.

**Comment by nhammond** [comment]
This is caused by the "n+1" problem, where DRF takes n+1 trips to the database to render a list of n objects. For deeply nested objects, performance degrades exponentially with depth.

The solution is well understood and explained here:
http://ses4j.github.io/2015/11/23/optimizing-slow-django-rest-framework-performance/

However, prefetch_related and select_related are not compatible with django-polymorphic.

Recursive nesting may also make it difficult to retrieve a full object of arbitrary depth with prefetch_related.

**Comment by nhammond** [comment]
Moving away from django-polymorphic is a big project. A simpler short-term solution would be paginating list views in the browser to avoid rendering the full list of objects at once, plus using prefetch_related wherever it does not conflict with django-polymorphic.

**Comment by nhammond** [comment]
Creating a baseline for speed. With the one-step workflow below, I ran these commands in a loop to time how the call to run_request index api increases with number of runs.

```
for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20;
do
    loom run ten one=1;
    time loom show runs;
done
```

Workflow:
```
---
name: two
inputs:
- type: integer
  hint: Enter a number
  channel: one
outputs:
- type: integer
  channel: two
steps:
- name: one
  interpreter: python
  command: print {{ one }} + 1
  environment:
    docker_image: python:2.7
  resources:
    cores: '1'
    memory: '1'
  inputs:
  - type: integer
    channel: one
  outputs:
  - type: integer
    channel: two
    source:
      stream: stdout
```
