### ISSUE TITLE
Three questions when I use the loom engine to process NGS data

### ISSUE THREAD

**Issue by zhangzhen** [StanfordBioinformatics/loom#400]
There are questions when I use the loom engine to process NGS data:

1. Can I use a glob pattern to specify a channel? Is the concept "channel" insprited by Nextflow's channel? Are there differences between them?

An example in Nextflow shows that reads is an input channel that contains multiple files, and samples are an output channel that also contains multiple files.

```
process extractSRA {
  container 'inutano/sra-toolkit'

  input: file read from reads
  output: file '*.fastq.gz' into samples

  """
  fastq-dump --split-files --skip-technical --gzip $read
  """
}
```

2. Our lab produces every time sequencing data which consists of 24 runs. I find it is hard to write a pipeline to process the data without glob patterns. Could you please give me some hints to solve this problem?

3. I've read the design proposal "User facing workflow definition language". The workflow definition language has changed a lot since then. Could you please tell me how much of this proposal has been implemented?

Regards,
Zhen Zhang

**Comment by nhammond** [comment]
Question 1:

We are working on this feature. It is not available today, but I expect it to be released within the next month.

The workflow definition would look like this: 

```
input:
  - channel: reads
    type: file
outputs:
  - channel: samples
  - type: file
  - mode: scatter
  - source:
      filename: *.fastq.gz
command: fastq-dump --split-files --skip-technical --gzip {{read}}
environment:
  - docker_image: inutano/sra-toolkit
```
