### ISSUE TITLE
AssertionError when two sibling runs have same input channel

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#419]
Running the workflow below fails with an assertion error:
```
  File "/Users/s0198839/dev/loom/loom/loomengine/master/api/models/data_nodes.py", line 336, in clone
    assert clone.data_object is None
AssertionError
```

```
name: level0
steps:
  - name: level1
    inputs:
      - channel: i
        type: integer
        data:
          contents: 3
    command: echo {{i}}
    environment:
      docker_image: ubuntu
  - name: level1a
    inputs:
      - channel: i
        type: integer
        data:
          contents: 3
    command: echo {{i}}
    environment:
      docker_image: ubuntu
```
