### ISSUE TITLE
Failure handling multiple parallel inputs

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#423]
Running the template below results in this error:

[2017-07-17 21:43:16,281: ERROR/MainProcess] Task api.async._finish_task_attempt[909b890a-8b00-424a-88a0-062c432e4190] raised unexpected: Exception('Input dimensions do not match in group 0',)

```
name: bug
steps:
  - name: one
    command: echo -n 1 2 3
    environment:
      docker_image: ubuntu
    outputs:
      - channel: counter
        type: string
        mode: scatter
        source:
          stream: stdout
        parser:
          type: delimited
          options:
            delimiter: ' '
            trim: true
  - name: sorted_by_coordinates
    command: echo -n {{counter}}
    environment:
      docker_image: ubuntu
    inputs:
      - channel: counter
        type: string
    outputs:
      - channel: sorted_dedup_bai
        type: string
        source:
          stream: stdout
      - channel: sorted_dedup_bam
        type: string
        source:
          stream: stdout
  - name: base_recalibration
    inputs:
      - channel: sorted_dedup_bai
        type: string
      - channel: sorted_dedup_bam
        type: string
    steps:
      - name: base_recalibrator
        command: sleep 30; echo -n {{sorted_dedup_bai}}
        environment:
          docker_image: ubuntu
        inputs:
          - channel: sorted_dedup_bai
            type: string
          - channel: sorted_dedup_bam
            type: string
        outputs:
          - channel: recalibration_report
            type: string
            source:
              stream: stdout
      - name: printreads
        command: echo x
        environment:
          docker_image: ubuntu
        inputs:
          - channel: recalibration_report
            type: string
          - channel: sorted_dedup_bai
            type: string
          - channel: sorted_dedup_bam
            type: string
```
