### ISSUE TITLE
Failure in task "Resolve release version URL" for EPEL repo

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#443]
****************************************** changed: [10.4.20.9] TASK [docker : start and enable docker] **************************************** changed: [10.4.20.9] TASK [docker-py : Get release version from yum] ******************************** [WARNING]: Consider using yum module rather than running yum changed: [10.4.20.9] TASK [docker-py : Resolve release version URL, which could be a link, to a Fedora Project EPEL mirror.] *** fatal: [10.4.20.9]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Connection failure: timed out", "redirected": false, "status": -1, "url": "http://download.fedoraproject.org/pub/epel/7"} to retry, use: --limit @/loom-settings/playbooks/gcloud_run_task_attempt.retry PLAY RECAP ********************************************************************* 10.4.20.9 : ok=14 changed=10 unreachable=0 failed=1 localhost : ok=17 changed=10 unreachable=0 failed=0

**Comment by nhammond** [comment]
Occasional failures connecting to external repos are expected.

**Comment by nhammond** [comment]
Fixed in e75749551e6e55288e03723a4ef957745277e468.

"retries" doesn't work without "until". 

```
 - name: Resolve release version URL, which could be a link, to a Fedora Project EPEL mirror.
     uri: url=http://download.fedoraproject.org/pub/epel/{{release_version.stdout}}
     register: resolved_mirror
     retries: 10
     until: resolved_mirror.status and resolved_mirror.status==200
 - name: Add epel repository to yum.
   yum_repository:
     name: epel
     description: EPEL YUM repo
     baseurl: "{{resolved_mirror.url}}$basearch/"
```
